# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-app
  template:
    metadata:
      labels:
        app: map-app
    spec:
      containers:
        - name: map-app
          image: map-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
