apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-app
  template:
    metadata:
      labels:
        app: map-app
    spec:
      containers:
        # Container for the map application
        - name: map-app
          image: map-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://root@cockroachdb-public:26257/map?sslmode=disable"