apiVersion: v1
kind: Service
metadata:
  name: map-app-service # The name of the Service
spec:
  selector:
    app: hello-k8s # This selects Pods with the label 'app: hello-k8s'
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # The port exposed by the Service (port 80 for HTTP)
      targetPort: 5000 # The port in the container where the app is running (port 5000)
  type: ClusterIP