apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
spec:
  selector:
    app: hello-k8s
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP