apiVersion: v1
kind: Service
metadata:
  name: map-app-service
spec:
  selector:
    app: map-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP