
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  MYSQL_DATABASE: "mannekendata"
  MYSQL_USER: "manneken"
  MYSQL_PASSWORD: "manneken123"
  DATABASE_URL: "mysql://manneken:manneken123@mysql-shard-0.mysql-shard:3306/mannekendata"