apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-nuxt-app
  template:
    metadata:
      labels:
        app: data-nuxt-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql:8.0
          command:
            - bash
            - "-c"
            - |
              until mysql -h mysql-read -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "SELECT 1"; do
                echo "waiting for mysql..."
                sleep 2
              done
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
      containers:
        - name: data-nuxt-app
          image: data-nuxt-app-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mysql-secret
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
