   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: data-nuxt-app
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: data-nuxt-app
     template:
       metadata:
         labels:
           app: data-nuxt-app
       spec:
         containers:
           - name: data-nuxt-app
             image: data-nuxt-app-image
             imagePullPolicy: Never
             ports:
               - containerPort: 3000
             env:
               - name: DATABASE_URL
                 value: "mysql://manneken:manneken123@mysql-shard-0.mysql-shard:3306/mannekendata"
               - name: HOST
                 value: "0.0.0.0"
               - name: PORT
                 value: "3000"
               - name: NODE_ENV
                 value: "production"
               - name: NITRO_HOST
                 value: "0.0.0.0"
               - name: NITRO_PORT
                 value: "3000"
             startupProbe:
               tcpSocket:
                 port: 3000
               initialDelaySeconds: 30
               periodSeconds: 10
               failureThreshold: 30