apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-nuxt-app
  labels:
    app: data-nuxt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-nuxt-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-nuxt-app
    spec:
      containers:
        - name: data-nuxt-app
          image: data-nuxt-app-image:20241209203842
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://manneken:manneken123@mysql-shard-0.mysql-shard:3306/mannekendata"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: NITRO_HOST
              value: "0.0.0.0"
            - name: NITRO_PORT
              value: "3000"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"