apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-nuxt-app
  template:
    metadata:
      labels:
        app: data-nuxt-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -w1 mysql 3306; do echo waiting for mysql; sleep 2; done;"
      containers:
        - name: data-nuxt-app
          image: data-nuxt-app-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mysql-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DATABASE_URL
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
