apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-nuxt-app
  template:
    metadata:
      labels:
        app: data-nuxt-app
    spec:
      containers:
        - name: data-nuxt-app
          image: data-nuxt-app-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://root:root@mysql:3306/manneken"
