apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-nuxt-app
  template:
    metadata:
      labels:
        app: data-nuxt-app
    spec:
      containers:
        - name: data-nuxt-app
          image: data-nuxt-app-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 20
