apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress-no-rewrite
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /data-nuxt-app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-nuxt-app-service
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-home-service
                port:
                  number: 80

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress-with-rewrite
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /map-app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: map-app-service
                port:
                  number: 80
          - path: /bb-demo(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bb-demo-service
                port:
                  number: 80
          - path: /api(/|$)(.*) # Route for backend API
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
          - path: /frontend(/|$)(.*) # Route for frontend
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: camera-app-host
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: camera-app-service
              port:
                number: 80