apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    binlog_expire_logs_seconds=604800
    innodb_buffer_pool_size=128M
    innodb_flush_log_at_trx_commit=2
    innodb_log_buffer_size=32M
    innodb_max_dirty_pages_pct=90
    interactive_timeout=180
    max_connections=200
    thread_cache_size=16
    wait_timeout=180