apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mannekendata;
    USE mannekendata;

    -- Create shard registry table
    CREATE TABLE IF NOT EXISTS ShardRegistry (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shardId INT UNIQUE NOT NULL,
      host VARCHAR(255) NOT NULL,
      minKey BIGINT NOT NULL,
      maxKey BIGINT NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Initialize shard registry
    INSERT INTO ShardRegistry (shardId, host, minKey, maxKey)
    VALUES
      (0, 'mysql-shard-0.mysql-shard', 0, 500000),
      (1, 'mysql-shard-1.mysql-shard', 500001, 1000000)
    ON DUPLICATE KEY UPDATE
      host = VALUES(host),
      minKey = VALUES(minKey),
      maxKey = VALUES(maxKey);

    -- Create ANPRData table (existing)
    CREATE TABLE IF NOT EXISTS ANPRData (
      id INT AUTO_INCREMENT PRIMARY KEY,
      licensePlate VARCHAR(20) NOT NULL,
      timestamp TIMESTAMP NOT NULL,
      vehicleType VARCHAR(50),
      speed INT,
      location VARCHAR(100),
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      shardKey BIGINT
    );

    -- Create MapData table (existing)
    CREATE TABLE IF NOT EXISTS MapData (
      id INT AUTO_INCREMENT PRIMARY KEY,
      roadId VARCHAR(50) NOT NULL,
      roadName VARCHAR(100),
      vehicleDensity INT,
      avgSpeed INT,
      congestionLevel VARCHAR(50),
      accidentsReported INT,
      weatherCondition VARCHAR(100),
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      shardKey BIGINT
    );

    -- Create Formula table (existing)
    CREATE TABLE IF NOT EXISTS Formula (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shardKey BIGINT NOT NULL,
      formula TEXT NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    -- Create VideoRecord table (new - for camera service)
    CREATE TABLE IF NOT EXISTS VideoRecord (
      id INT AUTO_INCREMENT PRIMARY KEY,
      cameranumber VARCHAR(191) NOT NULL,
      numberplate VARCHAR(191) NOT NULL,
      typevehicule VARCHAR(191) NOT NULL,
      createat TIMESTAMP NOT NULL,
      shardKey BIGINT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_numberplate (numberplate),
      INDEX idx_cameranumber (cameranumber),
      INDEX idx_createat (createat),
      INDEX idx_shardKey (shardKey)
    );

    -- Create Intersection table (new - for external map service)
    CREATE TABLE IF NOT EXISTS Intersection (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(191) NOT NULL,
      x_coordinate INT NOT NULL,
      y_coordinate INT NOT NULL,
      shardKey BIGINT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_name (name),
      INDEX idx_shardKey (shardKey)
    );

    -- Create ExternalRoad table (new - for external map service)
    CREATE TABLE IF NOT EXISTS ExternalRoad (
      id INT AUTO_INCREMENT PRIMARY KEY,
      start_intersection INT NOT NULL,
      end_intersection INT NOT NULL,
      length INT NOT NULL,
      useable BOOLEAN NOT NULL DEFAULT true,
      shardKey BIGINT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_intersections (start_intersection, end_intersection),
      INDEX idx_shardKey (shardKey),
      FOREIGN KEY (start_intersection) REFERENCES Intersection(id),
      FOREIGN KEY (end_intersection) REFERENCES Intersection(id)
    );

    -- Add indexes for existing tables (preserved from original)
    CREATE INDEX IF NOT EXISTS idx_shardKey ON ANPRData(shardKey);
    CREATE INDEX IF NOT EXISTS idx_createdAt ON ANPRData(createdAt);
    CREATE INDEX IF NOT EXISTS idx_vehicleDensity ON MapData(vehicleDensity);
    CREATE INDEX IF NOT EXISTS idx_congestionLevel ON MapData(congestionLevel);
