apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mannekendata;
    CREATE USER IF NOT EXISTS 'manneken'@'%' IDENTIFIED BY 'manneken123';
    GRANT ALL PRIVILEGES ON mannekendata.* TO 'manneken'@'%';
    FLUSH PRIVILEGES;
