apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  primary.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    default_authentication_plugin=mysql_native_password
    bind-address=0.0.0.0
    skip-name-resolve
    max_connections=1000

  replica.cnf: |
    [mysqld]
    server-id=2
    log-bin=mysql-bin
    default_authentication_plugin=mysql_native_password
    bind-address=0.0.0.0
    skip-name-resolve
    max_connections=1000
    read_only=1
    super_read_only=1
