apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  primary.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog_format=ROW
    default_authentication_plugin=mysql_native_password

  replica.cnf: |
    [mysqld]
    server-id=2
    relay-log=mysql-relay-bin
    log-bin=mysql-bin
    binlog_format=ROW
    default_authentication_plugin=mysql_native_password
    read_only=1
    super_read_only=1
