apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None # Headless service for StatefulSet

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: ClusterIP # Load balancer for read replicas
