apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    [mysqld]
    log-bin=mysql-bin
    binlog_format=ROW
    server-id=1
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_slave_updates=ON
  replica.cnf: |
    [mysqld]
    server-id=${SERVER_ID}
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_slave_updates=ON
    read_only=ON
    super_read_only=ON
