apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    [mysqld]
    log-bin
    binlog_format=ROW
    default_authentication_plugin=mysql_native_password
  replica.cnf: |
    [mysqld]
    super-read-only
    default_authentication_plugin=mysql_native_password
